DROP TABLE IF EXISTS garage;

CREATE TABLE garage (
      id bigint generated by default as identity,
      piso integer,
      posicion integer,
      patente VARCHAR(255),
      tipo_auto VARCHAR(255),
      fecha_ingreso DATE,
      primary key (id)
 );