DROP TABLE IF EXISTS garage;

CREATE TABLE garage (
      id bigint generated by default as identity,
      piso integer,
      posicion integer,
      patente VARCHAR(255),
      tipo_auto VARCHAR(255),
      primary key (id)
 );

INSERT INTO garage (piso, posicion, patente, tipo_auto) VALUES
(1, 1, 'AE123FD', 'CAMIONETA'),
(1, 3, 'CD123AA', 'CAMIONETA'),
(2, 4, 'LEO123', 'AUTO'),
(2, 4, 'CHA999', 'AUTO');